package Screens;

//imports libraries
import java.awt.Color;
import mailConfig.Mail;

public class ContactCompany extends javax.swing.JFrame {

    //Holds darkness information from Communication class
    boolean isDark = Communication.isDark();

    //Holds language information from Communication class
    boolean isTurkish = Communication.isTurkish();

    /**
     * Creates new form GiveFeedback
     */
    public ContactCompany() {
        initComponents();

        //Calls setComponentsNames method
        setComponentsNames();

        //Checks language whether is Turkish or not
        //If Turkish option is selected from the application page, sets language as Turkish 
        if (isTurkish) {
            //Calls setTurkish method
            setTurkish();
        } else {
            //Calls setEnglish method
            setEnglish();
        }

        //Checks darkness whether it is Dark or not
        //If DarkTheme option is selected from the application page, sets background color as black
        if (isDark) {
            //Calls setDark method
            setDark();
        } else {
            //Calls setLight method
            setLight();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_contactText = new javax.swing.JTextArea();
        jLabel_handIcon = new javax.swing.JLabel();
        jComboBox_companies = new javax.swing.JComboBox<>();
        jButton_submitButton = new javax.swing.JButton();
        jLabel_contactUs = new javax.swing.JLabel();
        jLabel_chooseCompany = new javax.swing.JLabel();
        jButton_MainPage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton_darkThemeButton = new javax.swing.JButton();
        jButton_lightThemeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 78, 70));

        jTextArea_contactText.setColumns(20);
        jTextArea_contactText.setRows(5);
        jScrollPane1.setViewportView(jTextArea_contactText);

        jLabel_handIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finger.png"))); // NOI18N

        jComboBox_companies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Trendyol", "Amazon", "Hepsiburada", "N11" }));
        jComboBox_companies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_companiesActionPerformed(evt);
            }
        });

        jButton_submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_submitButton.setText("Submit");
        jButton_submitButton.setPreferredSize(new java.awt.Dimension(107, 25));
        jButton_submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitButtonActionPerformed(evt);
            }
        });

        jLabel_contactUs.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel_contactUs.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_contactUs.setText("contact us");

        jLabel_chooseCompany.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_chooseCompany.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_chooseCompany.setText("Choose Company");

        jButton_MainPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_MainPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_orange.png"))); // NOI18N
        jButton_MainPage.setText("Main Page");
        jButton_MainPage.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton_MainPage.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainPageActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jButton_darkThemeButton.setBackground(new java.awt.Color(51, 51, 51));
        jButton_darkThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_darkThemeButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_darkThemeButton.setMaximumSize(new java.awt.Dimension(104, 23));
        jButton_darkThemeButton.setMinimumSize(new java.awt.Dimension(104, 23));
        jButton_darkThemeButton.setPreferredSize(new java.awt.Dimension(104, 23));
        jButton_darkThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_darkThemeButtonActionPerformed(evt);
            }
        });

        jButton_lightThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_lightThemeButton.setText("LightTheme");
        jButton_lightThemeButton.setMaximumSize(new java.awt.Dimension(104, 23));
        jButton_lightThemeButton.setMinimumSize(new java.awt.Dimension(104, 23));
        jButton_lightThemeButton.setPreferredSize(new java.awt.Dimension(104, 23));
        jButton_lightThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lightThemeButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("TR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("EN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_darkThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel_contactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_lightThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_chooseCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_handIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_companies, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_darkThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_chooseCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_handIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_lightThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_companies, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_contactUs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_MainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitButtonActionPerformed

        //Holds choosen company name
        String company = (String) jComboBox_companies.getSelectedItem();

        //Holds choosen category name 
        String contactText = jTextArea_contactText.getText();

        //Sets new texts to the warningtext label 
        //If the company or category is not selected, it gives a warning
        if (company.equals(" ") && !(contactText.equals(""))) {
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Lütfen Firma Seçiniz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Please select company!");
            }

            //If the contact text or company is not selected, it gives a warning
        } else if (contactText.equals("") && !(company.equals(" "))) {
            //Sets new texts to the warningtext label 
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("İletişim bölümü boş bırakılamaz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Contact field can not be empty!");
            }

            //After sending mail successfully, an informing message appears on the page "Submitted Successfully, Email sended to Company!"
        } else if (contactText.equals("") && company.equals(" ")) {
            //Sets new texts to the warningtext label 
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Lütfen firma ve iletişim bölümlerini doldurunuz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("All fields should be filled!");
            }

        } //After sending mail successfully, an informing message appears on the page "Submitted Successfully, Email sended to Company!"
        else {

            //Creates a Mail object that holds the methods which includes Mail Configuration
            Mail mailSender = new Mail();

            //Sends an email to the relevant company which includes feedback
            mailSender.sendMail("Contact Company", contactText);

            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Başarıyla Gönderildi, Şirket Bilgilendirildi!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Submitted Successfully, Company has been informed!");
            }
        }
    }//GEN-LAST:event_jButton_submitButtonActionPerformed

    private void jButton_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainPageActionPerformed
        //SelectProcess page will switches to the DeleteFeedback page
        SelectProcess sp = new SelectProcess();
        sp.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_MainPageActionPerformed

    private void jComboBox_companiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_companiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_companiesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Calls setTurkish method
        setTurkish();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Calls setEnglish method
        setEnglish();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_darkThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_darkThemeButtonActionPerformed
        //Calls setDark method
        setDark();
    }//GEN-LAST:event_jButton_darkThemeButtonActionPerformed

    private void jButton_lightThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lightThemeButtonActionPerformed
        //Calls setLight method
        setLight();
    }//GEN-LAST:event_jButton_lightThemeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContactCompany().setVisible(true);
            }
        });
    }

    //Gives names to the components
    private void setComponentsNames() {
        jComboBox_companies.setName("companies");
        jLabel5.setName("warningText");
        jTextArea_contactText.setName("contactText");
        jButton_submitButton.setName("submitButton");
    }

    public void setDark() {
        //Sets color of panel as black
        jPanel1.setBackground(Color.black);

        //Sets color of text of "Choose Company" label as orange
        jLabel_chooseCompany.setForeground(new Color(255, 78, 70));

        //Sets isDark variable as True in Communication class
        Communication.setDarkness(true);
    }

    public void setLight() {
        //Sets color of panel as light
        jPanel1.setBackground(new Color(255, 78, 70));

        //Sets color of text of "Choose Company" label as black
        jLabel_chooseCompany.setForeground(Color.black);

        //Sets isDark variable as False in Communication class
        Communication.setDarkness(false);
    }

    public void setTurkish() {
        //Sets text of components as Turkish
        jLabel_chooseCompany.setText("Firma Seçiniz");
        jLabel_contactUs.setText("iletişime geç");
        jButton_submitButton.setText("Gönder");
        jButton_MainPage.setText("Ana Sayfa");
        jButton_darkThemeButton.setText("KoyuTema");
        jButton_lightThemeButton.setText("AçıkTema");

        //Sets isTurkish variable as True in Communication class
        Communication.setLanguage(true);
    }

    public void setEnglish() {
        //Sets text of components as English
        jLabel_chooseCompany.setText("Choose Company");
        jLabel_contactUs.setText("contuct us");
        jButton_submitButton.setText("Submit");
        jButton_MainPage.setText("Main Page");
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_lightThemeButton.setText("LightTheme");

        //Sets isTurkish variable as False in Communication class
        Communication.setLanguage(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_MainPage;
    private javax.swing.JButton jButton_darkThemeButton;
    private javax.swing.JButton jButton_lightThemeButton;
    private javax.swing.JButton jButton_submitButton;
    private javax.swing.JComboBox<String> jComboBox_companies;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_chooseCompany;
    private javax.swing.JLabel jLabel_contactUs;
    private javax.swing.JLabel jLabel_handIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_contactText;
    // End of variables declaration//GEN-END:variables
}
