package Screens;

//imports libraries
import java.sql.ResultSet;
import Connection.My_Connection;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import mailConfig.Mail;

public class GiveFeedback extends javax.swing.JFrame {

    //Holds darkness information from Communication class
    boolean isDark = Communication.isDark();

    //Holds language information from Communication class
    boolean isTurkish = Communication.isTurkish();

    //Holds star icons for rating with stars
    Icon yellowStar = new ImageIcon(getClass().getResource("/images/brightstar.png"));
    Icon greenStar = new ImageIcon(getClass().getResource("/images/green24star.png"));

    //Holds product rate
    //Initial rate value is zero
    private Integer productRate = 0;
    

    //Returns current rate
    public int getRate() {
        return productRate;
    }

    //Sets new rate
    public void setRate(int rate) {
        productRate = rate;
    }

    /**
     * Creates new form GiveFeedback
     */
    public GiveFeedback() {
        initComponents();

        //Calls setComponentsNames method
        setComponentsNames();

        //Checks language whether it is Turkish or not
        //If Turkish option is selected from the application page, sets language as Turkish current page
        if (isTurkish) {
            //Calls setTurkish method
            setTurkish();
        } else {
            //Calls setEnglish method
            setEnglish();
        }

        //Checks darkness whether it is Dark or not
        //If DarkTheme option is selected from the application page, sets background color as black
        if (isDark) {
            //Calls setDark method
            setDark();
        } else {
            //Calls setLight method
            setLight();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_feedbacktext = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_companies = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField_productID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_categories = new javax.swing.JComboBox<>();
        jButton_MainPage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_darkThemeButton = new javax.swing.JButton();
        jButton_lightThemeButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jTextArea_feedbacktext.setColumns(20);
        jTextArea_feedbacktext.setRows(5);
        jScrollPane1.setViewportView(jTextArea_feedbacktext);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Category");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finger.png"))); // NOI18N

        jComboBox_companies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Trendyol", "Amazon", "Hepsiburada", "N11" }));
        jComboBox_companies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_companiesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product ID:");

        jTextField_productID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_productIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Rate Product!");

        jButton_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_submit.setText("Submit");
        jButton_submit.setPreferredSize(new java.awt.Dimension(107, 25));
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping_woman.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("give feedback");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Company");

        jComboBox_categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Clothing", "Electronics", "Books", "Shoes", "PersonelCare", "FoodandBeverage" }));
        jComboBox_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriesActionPerformed(evt);
            }
        });

        jButton_MainPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MainPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_orange.png"))); // NOI18N
        jButton_MainPage.setText("Main Page");
        jButton_MainPage.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton_MainPage.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainPageActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("EN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("TR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_darkThemeButton.setBackground(new java.awt.Color(51, 51, 51));
        jButton_darkThemeButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_darkThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_darkThemeButtonActionPerformed(evt);
            }
        });

        jButton_lightThemeButton.setBackground(new java.awt.Color(255, 255, 255));
        jButton_lightThemeButton.setForeground(new java.awt.Color(51, 51, 51));
        jButton_lightThemeButton.setText("LightTheme");
        jButton_lightThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lightThemeButtonActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finger.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_lightThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_darkThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel12)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton_MainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_companies, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(209, 209, 209)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1))))
                                    .addComponent(jLabel9))
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_darkThemeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_lightThemeButton)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_companies, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_categories))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_MainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed

        //Holds choosen company name 
        String company = (String) jComboBox_companies.getSelectedItem();

        //Holds choosen category name 
        String category = (String) jComboBox_categories.getSelectedItem();

        //Holds feedback ID
        String productID = jTextField_productID.getText();

        //Holds customer feedback
        String feedback = jTextArea_feedbacktext.getText();
        
        //Gets username information entered from Login page
        int id_customer = Communication.getCustomerID();

        //Sets new texts to the warningtext label 
        //If the company or category is not selected, it gives a warning
        if (company.equals(" ") || category.equals(" ")) {
            //If Turkish language is selected sets warningtext label in Turkish
            if (Communication.isTurkish()) {
                jLabel5.setText("Lütfen Şirket ve Kategori Seçiniz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Please select company and category both!");
            }

        //If the product is not selected, it gives a warning
        } else if (productID.equals("")) {
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Ürün ID boş bırakılamaz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Product ID can not be empty!");
            }

         //If the feedback aread is empty, it gives a warning
        } else if (feedback.equals("")) {
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Yorum alanı boş bırakılamaz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("Feedback field can not be empty!");
            }
         //If the stars are not choosen, it gives a warning
        } else if (productRate == 0) {
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel5.setText("Yıldız seçmelisiniz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel5.setText("You should rate with stars!");
            }

        //If all fields are filled, the SQL query is executed
        } else {

            try {
                //Connects relevant database 
                My_Connection connection = new My_Connection("customerfeedbackmanagement");
                java.sql.Statement stm = connection.getcon().createStatement();

                //SQL query finds the product that user enters to find wheter it exists on the Database or not
                String sql = "select * from product where id_product = '" + productID + "'  ";

                //ResultSet object holds the tabular data returned by the method that execute the sql statements which quires the database 
                ResultSet rs = stm.executeQuery(sql);

                //Checks whether it exists on the Database or not
                //rs.next() returns true if stm.executeQuery(sql) find a productID that satisfies the sql query, otherwise it returns false
                if (rs.next()) {

                    //If there is a product on Database with entered productID and then below query runs and inserts the feedback
                    //String query = "Insert Into feedback (id_product,feedback_text,company_name,category,rate) VALUES(" + "'" + productID + "'," + "'" + feedback + "'," + "'" + company + "'," + "'" + category + "'," + "'" + productRate + "')";
                    String query = "Insert Into feedback (id_product,feedback_text,id_customer,company_name,category,rate) VALUES(" + "'" + productID + "'," + "'" + feedback + "'," + "'"+id_customer+"',"+     "'" + company + "'," + "'" + category + "'," + "'" + productRate + "')";
                    try {
                        //Insert a new data the feedback table based on the data that user choose from the GiveFeedback screen
                        stm.executeUpdate(query);

                    } catch (SQLException ex) {
                        //Throws an exception if a database query problem occurs
                        Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    //Creates a Mail object that holds the methods which includes Mail Configuration
                    Mail mailSender = new Mail();

                    //Sends an email to the relevant company which includes feedback
                    mailSender.sendMail("New Feedback Submission", feedback);

                    //After sending mail successfully, an informing message appears on the page 
                    if (Communication.isTurkish()) {
                        //If Turkish language is selected sets warningtext label in Turkish
                        jLabel5.setText("İşlem Başarılı, Firmaya Mail Gönderildi!");
                    } else {
                        //If Turkish language is not selected sets warningtext label in English
                        jLabel5.setText("Submitted Successfully, Email sended to Company!");
                    }

                } else {
                    //Sets new texts to the warningtext label 
                    if (Communication.isTurkish()) {
                        //If Turkish language is selected sets warningtext label in Turkish
                        jLabel5.setText("Böyle bir  Product ID bulunmamaktadır!");
                    } else {
                        //If Turkish language is not selected sets warningtext label in English
                        jLabel5.setText("There is no product with this product ID!");
                    }

                }
            } catch (SQLException ex) {
                //Throws an exception if a database query problem occurs
                Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered

    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered

    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited

    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited

    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited

    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited

    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited

    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(greenStar);
        jLabel12.setIcon(greenStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 1;
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(greenStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 2;
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 3;
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(yellowStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 4;
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(yellowStar);
        jLabel14.setIcon(yellowStar);

        //Sets product rate
        productRate = 5;
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainPageActionPerformed
        SelectProcess sp = new SelectProcess();
        sp.show();
        dispose();
    }//GEN-LAST:event_jButton_MainPageActionPerformed

    private void jComboBox_companiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_companiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_companiesActionPerformed

    private void jTextField_productIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_productIDActionPerformed

    }//GEN-LAST:event_jTextField_productIDActionPerformed

    private void jComboBox_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Calls setTurkish method
        setTurkish();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Calls setTurkish method
        setEnglish();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_darkThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_darkThemeButtonActionPerformed
        //Calls setDark method
        setDark();
    }//GEN-LAST:event_jButton_darkThemeButtonActionPerformed

    private void jButton_lightThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lightThemeButtonActionPerformed
        //Calls setLight method
        setLight();
    }//GEN-LAST:event_jButton_lightThemeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GiveFeedback().setVisible(true);
            }
        });
    }

    //Gives names to the components
    private void setComponentsNames() {
        jComboBox_companies.setName("companies");
        jComboBox_categories.setName("categories");
        jLabel5.setName("warningText");
        jTextArea_feedbacktext.setName("feedbackText");
        jTextField_productID.setName("productID");
        jButton_submit.setName("submitButton");
    }

    public void setTurkish() {
        //Sets text of components as Turkish
        jLabel3.setText("Firma Seçiniz");
        jLabel1.setText("Kategori Seçiniz");
        jLabel6.setText("Ürün ID:");
        jLabel9.setText("yorum bırak");
        jLabel7.setText("Ürünü Değerlendir!");
        jButton_submit.setText("Gönder");
        jButton_MainPage.setText("Ana Sayfa");
        jButton_darkThemeButton.setText("KoyuTema");
        jButton_lightThemeButton.setText("AçıkTema");

        //Sets isTurksh variable as True in Communication class
        Communication.setLanguage(true);
    }

    public void setEnglish() {
        //Sets text of components as Turkish
        jLabel3.setText("Choose Company");
        jLabel1.setText("Select Category");
        jLabel6.setText("Product ID:");
        jLabel9.setText("give feedback");
        jLabel7.setText("Rate Product!");
        jButton_submit.setText("Submit");
        jButton_MainPage.setText("Main Page");
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_lightThemeButton.setText("LightTheme");

        //Sets isTurksh variable as False in Communication class
        Communication.setLanguage(false);
    }

    public void setDark() {
        //Sets color of panel as black
        jPanel1.setBackground(Color.black);

        //Sets isDark variable as True in Communication class
        Communication.setDarkness(true);
    }

    public void setLight() {
        //Sets color of panel as light
        jPanel1.setBackground(new Color(51, 102, 255));

        //Sets isDark variable as False in Communication class
        Communication.setDarkness(false);
    }
    
    
    //Sets customer ID on the Communication page
    public void setCustomerID(int id) {
        Communication.setCustomerID(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_MainPage;
    private javax.swing.JButton jButton_darkThemeButton;
    private javax.swing.JButton jButton_lightThemeButton;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBox_categories;
    private javax.swing.JComboBox<String> jComboBox_companies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_feedbacktext;
    private javax.swing.JTextField jTextField_productID;
    // End of variables declaration//GEN-END:variables
}
