package Screens;

//imports libraries
import java.awt.Color;

public class SelectProcess extends javax.swing.JFrame {

    //Holds darkness information from Communication class
    boolean isDark = Communication.isDark();

    //Holds language information from Communication class
    boolean isTurkish = Communication.isTurkish();

    public SelectProcess() {
        initComponents();

        //Checks language whether is Turkish or not
        //If Turkish option is selected from the application page, sets language as Turkish current page
        if (isTurkish) {
            //Calls setTurkish method
            setTurkish();
        } else {
            //Calls setEnglish method
            setEnglish();
        }

        //Checks darkness whether is Dark or not
        //If DarkTheme option is selected from the application page, sets background color as black
        if (isDark) {
          //Calls setDark method
            setDark();
        } else {
             //Calls setLight method
            setLight();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_giveFeedback = new javax.swing.JButton();
        jButton_deleteFeedback = new javax.swing.JButton();
        jButton_updateFeedback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_contactCompany = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_setTurkish = new javax.swing.JButton();
        jButton_setEnglish = new javax.swing.JButton();
        jButton_darkThemeButton = new javax.swing.JButton();
        jButton_lightThemeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 208, 63));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("What Do You Want?");

        jButton_giveFeedback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_giveFeedback.setForeground(new java.awt.Color(51, 51, 255));
        jButton_giveFeedback.setText("Give Feedback");
        jButton_giveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_giveFeedbackActionPerformed(evt);
            }
        });

        jButton_deleteFeedback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_deleteFeedback.setForeground(new java.awt.Color(51, 51, 255));
        jButton_deleteFeedback.setText("Delete My Feedback");
        jButton_deleteFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteFeedbackActionPerformed(evt);
            }
        });

        jButton_updateFeedback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_updateFeedback.setForeground(new java.awt.Color(51, 51, 255));
        jButton_updateFeedback.setText("Update My Feedback");
        jButton_updateFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateFeedbackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feedback.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jButton_contactCompany.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_contactCompany.setForeground(new java.awt.Color(51, 51, 255));
        jButton_contactCompany.setText("Contact Company");
        jButton_contactCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_contactCompanyActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N

        jButton_setTurkish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_setTurkish.setText("TR");
        jButton_setTurkish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_setTurkishActionPerformed(evt);
            }
        });

        jButton_setEnglish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_setEnglish.setText("EN");
        jButton_setEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_setEnglishActionPerformed(evt);
            }
        });

        jButton_darkThemeButton.setBackground(new java.awt.Color(51, 51, 51));
        jButton_darkThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_darkThemeButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_darkThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_darkThemeButtonActionPerformed(evt);
            }
        });

        jButton_lightThemeButton.setBackground(new java.awt.Color(255, 255, 255));
        jButton_lightThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_lightThemeButton.setText("LightTheme");
        jButton_lightThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lightThemeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton_giveFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_updateFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_deleteFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_contactCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_lightThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_darkThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_setTurkish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_setEnglish)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_setTurkish)
                            .addComponent(jButton_setEnglish)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_darkThemeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_lightThemeButton)))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton_giveFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton_updateFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_deleteFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_contactCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_giveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_giveFeedbackActionPerformed
        //SelectProcess page will switches to the GiveFeedback page
        GiveFeedback gf = new GiveFeedback();
        gf.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_giveFeedbackActionPerformed

    private void jButton_updateFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateFeedbackActionPerformed
        //Sets new texts to the warningtext label 
        jLabel5.setText("You are being redirected to the comment deletion page...");

        //SelectProcess page will switches to the UpdateFeedback page
        UpdateFeedback uf = new UpdateFeedback();
        uf.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_updateFeedbackActionPerformed

    private void jButton_deleteFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteFeedbackActionPerformed
        //SelectProcess page will switches to the DeleteFeedback page
        DeleteFeedback df = new DeleteFeedback();
        df.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_deleteFeedbackActionPerformed

    private void jButton_contactCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_contactCompanyActionPerformed
        //SelectProcess page will switches to the DeleteFeedback page
        ContactCompany cc = new ContactCompany();
        cc.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_contactCompanyActionPerformed

    private void jButton_darkThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_darkThemeButtonActionPerformed
        //Calls setDark method
        setDark();
    }//GEN-LAST:event_jButton_darkThemeButtonActionPerformed

    private void jButton_lightThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lightThemeButtonActionPerformed
        //Calls setLight method
        setLight();
    }//GEN-LAST:event_jButton_lightThemeButtonActionPerformed

    private void jButton_setTurkishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_setTurkishActionPerformed
        //Calls setTurkish method
        setTurkish();
    }//GEN-LAST:event_jButton_setTurkishActionPerformed

    private void jButton_setEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_setEnglishActionPerformed
        //Calls setEngish method
        setEnglish();
    }//GEN-LAST:event_jButton_setEnglishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectProcess().setVisible(true);
            }
        });
    }

    //Gives names to the components
    private void setComponentsNames() {
        jButton_deleteFeedback.setName("deleteFeedbackButton");
        jButton_giveFeedback.setName("giveFeedbackButton");
        jButton_updateFeedback.setName("updateFeedbackButton");

    }

    public void setTurkish() {
        //Sets text of components as Turkish
        jLabel1.setText("Ne Yapmak İstersiniz?");
        jButton_updateFeedback.setText("Yorumumu Güncelle");
        jButton_giveFeedback.setText("Yorum Yap");
        jButton_deleteFeedback.setText("Yorumumu Sil");
        jButton_contactCompany.setText("Firmayla İletişime Geç");
        jButton_darkThemeButton.setText("KoyuTema");
        jButton_lightThemeButton.setText("AçıkTema");

        //Sets isTurksh variable as True in Communication class
        Communication.setLanguage(true);
    }

    public void setEnglish() {
        //Sets text of components as English
        jLabel1.setText("What Do You Want?");
        jButton_updateFeedback.setText("Update My Feedback");
        jButton_giveFeedback.setText("Give feedback");
        jButton_deleteFeedback.setText("Delete My Feedback");
        jButton_contactCompany.setText("Contact Company");
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_lightThemeButton.setText("LightTheme");

        //Sets isTurksh variable as False in Communication class
        Communication.setLanguage(false);
    }

    public void setDark() {
        //Sets color of panel as black
        jPanel1.setBackground(Color.black);

        //Sets isDark variable as True in Communication class
        Communication.setDarkness(true);
    }

    public void setLight() {
        //Sets color of panel as light
        jPanel1.setBackground(new Color(244, 208, 63));

        //Sets isDark variable as False in Communication class
        Communication.setDarkness(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_contactCompany;
    private javax.swing.JButton jButton_darkThemeButton;
    private javax.swing.JButton jButton_deleteFeedback;
    private javax.swing.JButton jButton_giveFeedback;
    private javax.swing.JButton jButton_lightThemeButton;
    private javax.swing.JButton jButton_setEnglish;
    private javax.swing.JButton jButton_setTurkish;
    private javax.swing.JButton jButton_updateFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
