package Screens;

//imports libraries
import Connection.My_Connection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class UpdateFeedback extends javax.swing.JFrame {

    //Holds darkness information from Communication class
    boolean isDark = Communication.isDark();

    //Holds language information from Communication class
    boolean isTurkish = Communication.isTurkish();

    //Holds star icons for rating stars
    Icon yellowStar = new ImageIcon(getClass().getResource("/images/brightstar.png"));
    Icon greenStar = new ImageIcon(getClass().getResource("/images/green24star.png"));

    //Holds product rate
    //Initial rate value is zero
    private int productRate = 0;

    public UpdateFeedback() {
        initComponents();

        //Calls setComponentsNames method
        setComponentsNames();

        //Checks language whether it is Turkish or not
        //If Turkish option is selected from the application page, sets language as Turkish current page
        if (isTurkish) {
            //Calls setTurkish method
            setTurkish();
        } else {
            //Calls setEnglish method
            setEnglish();
        }

        //Checks darkness whether it is Dark or not
        //If DarkTheme option is selected from the application page, sets background color as black
        if (isDark) {
            //Calls setDark method
            setDark();
        } else {
            //Calls setLight method
            setLight();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_feedbacktext = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_companies = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField_feedBackID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_categories = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton_MainPage = new javax.swing.JButton();
        jButton_darkThemeButton = new javax.swing.JButton();
        jButton_lightThemeButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 1, 244));

        jTextArea_feedbacktext.setColumns(20);
        jTextArea_feedbacktext.setRows(5);
        jScrollPane1.setViewportView(jTextArea_feedbacktext);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Select Category");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finger.png"))); // NOI18N

        jComboBox_companies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Trendyol", "Amazon", "Hepsiburada", "N11" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Feedback ID:");

        jTextField_feedBackID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_feedBackIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Rate Product!");

        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update.setText("Update!");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-mall.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("update feedback");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green24star.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Choose Company");

        jComboBox_categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Clothing", "Electronics", "Books", "Shoes", "PersonelCare", "FoodandBeverage" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_MainPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MainPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_orange.png"))); // NOI18N
        jButton_MainPage.setText("Main Page");
        jButton_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainPageActionPerformed(evt);
            }
        });

        jButton_darkThemeButton.setBackground(new java.awt.Color(51, 51, 51));
        jButton_darkThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_darkThemeButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_darkThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_darkThemeButtonActionPerformed(evt);
            }
        });

        jButton_lightThemeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_lightThemeButton.setText("LightTheme");
        jButton_lightThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lightThemeButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("TR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("EN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finger.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_lightThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_companies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox_categories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(65, 65, 65))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_feedBackID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton_MainPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_darkThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_darkThemeButton)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_companies, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTextField_feedBackID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton_lightThemeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_MainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed

        //Holds choosen company name 
        String company = (String) jComboBox_companies.getSelectedItem();

        //Holds choosen category name 
        String category = (String) jComboBox_categories.getSelectedItem();

        //Holds feedback ID
        String feedbackID = jTextField_feedBackID.getText();

        //Holds customer feedback
        String feedback = jTextArea_feedbacktext.getText();
        
        //Holds customer ID 
        int customerID = Communication.getCustomerID();

        //If  no company or category is selected, warning message appears on the page
        if (company.equals(" ") || category.equals(" ")) {
            //Sets new texts to the warningtext label 
            if (Communication.isTurkish()) {
                //If Turkish language is selected sets warningtext label in Turkish
                jLabel4.setText("Lütfen firma ve kategori seçiniz!");
            } else {
                //If Turkish language is not selected sets warningtext label in English
                jLabel4.setText("Please select company and category both!");
            }
            //If  feedbackID  is empty, warning message appears on the page
        } else if (feedbackID.equals("")) {

            //If Turkish language is selected sets warningtext label in Turkish
            if (Communication.isTurkish()) {
                jLabel4.setText("Yorum ID alanı boş bırakılamaz!");

                //If Turkish language is not selected sets warningtext label in English
            } else {
                jLabel4.setText("Feedback ID can not be empty!");
            }
            //If  feedback field  is empty, warning message appears on the page
        } else if (feedback.equals("")) {

            //If Turkish language is selected sets warningtext label in Turkish
            if (Communication.isTurkish()) {
                jLabel4.setText("Yorum alanı boş bırakılamaz!");

                //If Turkish language is not selected sets warningtext label in English
            } else {
                jLabel4.setText("Feedback field can not be empty!");
            }

            //If  rate stars are empty, warning message appears on the page   
        } else if (productRate == 0) {

            //If Turkish language is selected sets warningtext label in Turkish
            if (Communication.isTurkish()) {
                jLabel4.setText("Yıldız seçmelisiniz!");

                //If Turkish language is not selected sets warningtext label in English
            } else {
                jLabel4.setText("You should rate with stars!");
            }

            //If all fields are filled and length of password is equal or grater than 8, SQL query runs  
        } else {

            try {
                //Connects relevant database 
                My_Connection connection = new My_Connection("customerfeedbackmanagement");
                java.sql.Statement stm = connection.getcon().createStatement();

                //SQL query finds the feedbackID that user enters to find wheter it exists on the Database or not
                //String sql = "select * from feedback where id_feedback = '" + feedbackID + "'  ";

                 String sql = "select * from feedback where id_feedback = '" + feedbackID + "'  and id_customer='" + customerID + "'";
                //ResultSet object holds the tabular data returned by the method that execute the sql statements which quires the database 
                ResultSet rs = stm.executeQuery(sql);

                //Checks wheter productID exists on the Database or not
                //rs.next() returns true if stm.executeQuery(sql) find a productID that satisfies the sql query, otherwise it returns false
                if (rs.next()) {
                    //Query for updating the feedback table based on the data that user choose from the UpdateFeedback screen
                    String query = "UPDATE feedback SET feedback_text= '" + feedback + "' ,company_name= '" + company + "' ,category= '" + category + "' ,rate='" + productRate + "' where id_feedback= " + feedbackID + "  ";

                    try {
                        //Updates the feedback table based on the data that user choose from the GiveFeedback screen
                        stm.executeUpdate(query);
                    } catch (SQLException ex) {
                        //Throws an exception if a database query problem occurs
                        Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //Sets new texts to the warningtext label 
                    if (Communication.isTurkish()) {
                        //If Turkish language is selected sets warningtext label in Turkish
                        jLabel4.setText("Başarıyla Güncellendi!");
                    } else {
                        //If Turkish language is not selected sets warningtext label in English
                        jLabel4.setText("Updated Successfully!");
                    }

                } else {
                    if (Communication.isTurkish()) {
                        //If Turkish language is selected sets warningtext label in Turkish
                        jLabel4.setText("Böyle bir Yorum ID bulunmamaktadır!");
                    } else {
                        //If Turkish language is not selected sets warningtext label in English
                        jLabel4.setText("There is no feedback with this Feedback ID!");
                    }
                    //Sets new texts to the warningtext label 

                }
            } catch (SQLException ex) {
                //Throws an exception if a database query problem occurs
                Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered

    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered

    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited

    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited

    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited

    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited

    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited

    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(greenStar);
        jLabel12.setIcon(greenStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 1;
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(greenStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 2;
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(greenStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 3;
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(yellowStar);
        jLabel14.setIcon(greenStar);

        //Sets product rate
        productRate = 4;
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        //Changes the colors of stars based on the chosen stars
        jLabel10.setIcon(yellowStar);
        jLabel11.setIcon(yellowStar);
        jLabel12.setIcon(yellowStar);
        jLabel13.setIcon(yellowStar);
        jLabel14.setIcon(yellowStar);

        //Sets product rate
        productRate = 5;
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jTextField_feedBackIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_feedBackIDActionPerformed
        //Holds choosen company name as String
        String company = (String) jComboBox_companies.getSelectedItem();

        //Holds choosen category name as String
        String category = (String) jComboBox_categories.getSelectedItem();

        //Holds product ID
        String productID = jTextField_feedBackID.getText();

        //Holds customer feedback
        String feedback = jTextArea_feedbacktext.getText();

        if (company.equals(" ") || category.equals(" ")) {
            //Sets new texts to the warningtext label 
            jLabel4.setText("Please select company and category both!");

        } else if (productID.equals("")) {
            //Sets new texts to the warningtext label 
            jLabel4.setText("Feedback ID can not be empty!");
        } else if (productRate == 0) {
            //Sets new texts to the warningtext label 
            jLabel4.setText("You should rate with stars!");
        } else if (feedback.equals("")) {
            //Sets new texts to the warningtext label 
            jLabel4.setText("Feedback field can not be empty!");
        } else {

            try {
                //Connects relevant database 
                My_Connection connection = new My_Connection("customerfeedbackmanagement");
                java.sql.Statement stm = connection.getcon().createStatement();

                //SQL query finds the feedbackID that user enters to find wheter it exists on the Database or not
                String sql = "select * from feedback where id_feedback = '" + productID + "'  ";

                //ResultSet object holds the tabular data returned by the method that execute the sql statements which quires the database 
                ResultSet rs = stm.executeQuery(sql);

                //Checks wheter productID exists on the Database or not
                //rs.next() returns true if stm.executeQuery(sql) find a productID that satisfies the sql query, otherwise it returns false
                if (rs.next()) {
                    //Query for updating the feedback table based on the data that user choose from the UpdateFeedback screen
                    String query = "UPDATE feedback SET feedback_text= '" + feedback + "' ,company_name= '" + company + "' ,category= '" + category + "' ,rate='" + productRate + "' where id_feedback= " + productID + "  ";

                    try {
                        //Updates the feedback table based on the data that user choose from the GiveFeedback screen
                        stm.executeUpdate(query);
                    } catch (SQLException ex) {
                        //Throws an exception if a database query problem occurs
                        Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //Sets new texts to the warningtext label 
                    jLabel4.setText("Updated Successfully!");

                } else {
                    //Sets new texts to the warningtext label 
                    jLabel4.setText("There is no feedback with this Feedback ID!");
                }
            } catch (SQLException ex) {
                //Throws an exception if a database query problem occurs
                Logger.getLogger(UpdateFeedback.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTextField_feedBackIDActionPerformed

    private void jButton_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainPageActionPerformed
        //SelectProcess page will switches to the DeleteFeedback page
        SelectProcess sp = new SelectProcess();
        sp.show();

        //Disappears current page
        dispose();
    }//GEN-LAST:event_jButton_MainPageActionPerformed

    private void jButton_darkThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_darkThemeButtonActionPerformed
        //Calls setDark method
        setDark();
    }//GEN-LAST:event_jButton_darkThemeButtonActionPerformed

    private void jButton_lightThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lightThemeButtonActionPerformed
        //Calls setLight method
        setLight();
    }//GEN-LAST:event_jButton_lightThemeButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Calls setTurkish method
        setTurkish();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Calls setEnglish method
        setEnglish();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateFeedback().setVisible(true);
            }
        });
    }

    //Gives names to the components
    private void setComponentsNames() {
        jComboBox_companies.setName("companies");
        jComboBox_categories.setName("categories");
        jLabel4.setName("warningText");
        jTextArea_feedbacktext.setName("feedbackText");
        jTextField_feedBackID.setName("feedBackID");
        jButton_update.setName("updateButton");
    }

    public int getRate() {
        return productRate;
    }

    public void setRate(int rate) {
        productRate = rate;
    }

    public void setDark() {
        //Sets color of panel as black
        jPanel1.setBackground(Color.black);

        //Sets isDark variable as True in Communication class
        Communication.setDarkness(true);
    }

    public void setLight() {
        //Sets color of panel as light
        jPanel1.setBackground(new Color(248, 1, 244));

        //Sets isDark variable as False in Communication class
        Communication.setDarkness(false);
    }

    public void setTurkish() {
        //Sets text of components as Turkish
        jLabel3.setText("Firma Seçiniz");
        jLabel1.setText("Kategori Seçiniz");
        jLabel6.setText("Yorum ID:");
        jLabel9.setText("yorum güncelle");
        jLabel7.setText("Ürünü Değerlendir!");
        jButton_update.setText("Gönder");
        jButton_MainPage.setText("Ana Sayfa");
        jButton_darkThemeButton.setText("KoyuTema");
        jButton_lightThemeButton.setText("AçıkTema");

        //Sets isTurkish variable as True in Communication class
        Communication.setLanguage(true);
    }

    public void setEnglish() {
        //Sets text of components as English
        jLabel3.setText("Choose Company");
        jLabel1.setText("Select Category");
        jLabel6.setText("Feedback ID:");
        jLabel9.setText("update feedback");
        jLabel7.setText("Rate Product!");
        jButton_update.setText("Submit");
        jButton_MainPage.setText("Main Page");
        jButton_darkThemeButton.setText("DarkTheme");
        jButton_lightThemeButton.setText("LightTheme");

        //Sets isTurkish variable as False in Communication class
        Communication.setLanguage(false);
    }
    
    //Sets customer ID on the Communication page
     public void setCustomerID(int id) {
        Communication.setCustomerID(id);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_MainPage;
    private javax.swing.JButton jButton_darkThemeButton;
    private javax.swing.JButton jButton_lightThemeButton;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_categories;
    private javax.swing.JComboBox<String> jComboBox_companies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_feedbacktext;
    private javax.swing.JTextField jTextField_feedBackID;
    // End of variables declaration//GEN-END:variables
}
